# Generated by Django 4.1.5 on 2023-01-17 00:16

import app.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bot_message_alter_user_managers_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Токен для tg бота'),
        ),
        migrations.AddField(
            model_name='bot',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Бота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_body',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель сообщения'),
            preserve_default=False,
        ),
    ]
