# Generated by Django 4.1.5 on 2023-01-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_managers_bot_bot_token_bot_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bot',
        ),
    ]
