# Generated by Django 4.1.5 on 2023-01-17 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_message_bot_alter_bot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время отправления'),
        ),
    ]
